% Compare the original baseline with the final retained switching model.
projectDir = fileparts(fileparts(mfilename('fullpath')));
resultsDir = fullfile(projectDir,'results');

baseline02 = load(fullfile(resultsDir,'acac_req6_0p2A_results.mat'),'w');
final02 = load(fullfile(resultsDir,'robust_final_load_02A.mat'),'w');
figureHandle = figure('Visible','off','Color','w','Position',[100 100 1100 680]);
tiledlayout(2,1,'TileSpacing','compact');
index = baseline02.w.t>=0.82 & baseline02.w.t<=0.84;
nexttile;
plot(baseline02.w.t(index),baseline02.w.vin(index),'k','LineWidth',1.0);
hold on;
plot(baseline02.w.t(index),baseline02.w.iin(index)*36,'b');
plot(final02.w.t(index),final02.w.iin(index)*36,'r--');
grid on; ylabel('Voltage (V), current x 36 (A)');
legend('Vin','Iin baseline x 36','Iin final x 36','Location','best');
title('36 V / 0.2 A: same coherent-window waveform scale');
nexttile;
index = abs(baseline02.w.t-0.84)<=0.002;
plot(baseline02.w.t(index),baseline02.w.vin(index)/36,'k','LineWidth',1.0);
hold on;
plot(baseline02.w.t(index),baseline02.w.iin(index),'b');
plot(final02.w.t(index),final02.w.iin(index),'r--');
grid on; xlabel('Time (s)'); ylabel('Normalized Vin, Iin (A)');
legend('Vin / 36','Iin baseline','Iin final','Location','best');
title('Zero-crossing zoom, +/- 2 ms');
exportgraphics(figureHandle,fullfile(resultsDir,'robust_02A_before_after.png'),'Resolution',180);
close(figureHandle);

baseline31 = load(fullfile(resultsDir,'acac_req7_31V_results.mat'),'w');
final31 = load(fullfile(resultsDir,'robust_final_line_31V.mat'),'w');
figureHandle = figure('Visible','off','Color','w','Position',[100 100 1100 820]);
tiledlayout(3,1,'TileSpacing','compact');
index = baseline31.w.t>=0.82 & baseline31.w.t<=0.84;
nexttile;
plot(baseline31.w.t(index),baseline31.w.iin(index),'b'); hold on;
plot(final31.w.t(index),final31.w.iin(index),'r--');
grid on; ylabel('PFC input current (A)');
legend('Baseline','Final','Location','best');
title('31 V / 2 A: retained physical current and DC-link behavior');
nexttile;
plot(baseline31.w.t(index),baseline31.w.vdc(index),'b'); hold on;
plot(final31.w.t(index),final31.w.vdc(index),'r--');
grid on; ylabel('Vdc (V)'); legend('Baseline','Final','Location','best');
nexttile;
plot(baseline31.w.t(index),baseline31.w.idc_pfc(index),'b'); hold on;
plot(final31.w.t(index),final31.w.idc_pfc(index),'r--');
plot(baseline31.w.t(index),baseline31.w.idc_inverter(index),'c');
plot(final31.w.t(index),final31.w.idc_inverter(index),'m--');
grid on; xlabel('Time (s)'); ylabel('DC branch currents (A)');
legend('PFC baseline','PFC final','VSI baseline','VSI final','Location','best');
exportgraphics(figureHandle,fullfile(resultsDir,'robust_31V_before_after.png'),'Resolution',180);
close(figureHandle);
